### ISSUE TITLE
Clinical Insights Overview documentation

### ISSUE THREAD

**Issue by bhargav01** [ibm-cloud-docs/wh-acd#2]
The opening line in [this ](https://cloud.ibm.com/docs/wh-acd?topic=wh-acd-clinical_insights_overview)doc talks about 'annotator', its pretty confusing.
It should be 'Clinical Insights' right?

![image](https://user-images.githubusercontent.com/28785543/83503028-1890e500-a4e0-11ea-9ece-0e2564d5ea39.png)

**Comment by srcarrier** [comment]
Thanks for the feedback @bhargav01 
_"Clinical Insights"_ is a capability provided through _"Annotator for Clinical Data"_. That's the message we were trying to convey there.
I take your point though.
Would the following intro make more sense?
> The clinical insights feature is a ready-to-use annotation capability within Watson Annotator for Clinical Data that provides critical contextual information for problems, procedures, and medications identified in the text.

**Comment by bhargav01** [comment]
Thanks for looking into it @srcarrier . Yes, that makes more sense.
